########## BACKUP DADOS #########
############ REMOTO #############

# NOMES MAIÚSCULOS DEVEM SER ALTERADOS COM OS DADOS DOS CAMINHOS DAS PASTAS DE CADA CLIENTE.
# ESSE BACKUP É UTILIZADO PARA CONEXÃO EM UM SERVIDOR DE ARQUIVOS REMOTO.

#CONEXÃO COM O SERVIDOR E MONTAGEM DO DISCO1 ONDE VAI SER SALVO OS DADOS DO SERVIDOR
mount -t smbfs -o  username=USER,password=SENHA //192.168.1.150/BACKUPS  /DISCO1/

#SINCRONIZAÇÃO DOS DADOS PARA O DISCO1
/usr/bin/rsync -avx  /DADOS/ /DISCO1

#DESMONTANDO O DISCO1
umount /DISCO1

